version: '3.9'
services:
    pizzly-db:
        image: postgres
        container_name: nango-db
        environment:
            POSTGRES_PASSWORD: nango
            POSTGRES_USER: nango
            POSTGRES_DB: nango
        ports:
            - '5432:5432'
        networks:
            - pizzly

    pizzly-server:
        image: nango.docker.scarf.sh/nangohq/pizzly-server
        container_name: pizzly-server
        restart: always
        env_file:
            - .env
        ports:
            - '443:443'
        depends_on:
            - pizzly-db
        networks:
            - pizzly
networks:
    pizzly:
